apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    namespace: loki
type: Opaque
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:KZX5Idh+TQ5IvFchm5xxPcAD7NwrSUdE6V0=,iv:0P8krcxXTKww/c3mO7l+eO2IABxvMcrEk0bjU2OUdx4=,tag:rouKTdm4sbtSrhy6fXwAKg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fzLLJjNUfK/MdmZ8X5o6cJcp6+RpHMtXreS1H8fwTajBpG+4g20UU6gCRudbLdrD6tz6gvNEYA25p8cxAgySOw==,iv:1GznFIq0UthLkz/6YSN+nDnpT1hcmN571QK7zUUaCac=,tag:SJzxIZ+2A0WGJd+Lsz1UfA==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UVlhaFlKWG1sSnE1VXJV
            SXFnRHFiR1ZvK3ljNEhrU2pFak5LbVNjbFNJCkdmOGF3SFpwaGdCbnQvamVCMXJq
            RHMvaFppQXp5dHd3ZVhNWkx0R0E3T0UKLS0tIEVCdHhWS3VXZE44N0IvVzNSaEZN
            RENRRzR6eTVRVDVCTXVCK0hjOUNSTTAKBSVFP8/jrwqYnekhopBT/v2NkDWX2M3y
            PiZbmR3gopzRtE4rQmfpWZFeePUXzGuC1pwSggkqv4PYwpC3JiZQDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T07:55:04Z"
    mac: ENC[AES256_GCM,data:ENZhjdHwVnlO4KqOrDirFwC1aaSxp1uH6hXdiZa5yRbg/+m0Gk3mtsocyX55nbmus2BLYqdR+GGDr3vWgUv7/ynKtOVQYEdT6uFmc9wU9iOxxlE64ixzd5NVv0JU3wndwr4Rjm3kq+KS8YI3xKyzzO0yNNbzo1bev1DTl9yXntE=,iv:nkTAWd/x+R9a7SgKT5H5kRVBYOIAXDA2j1IAPgbCeuI=,tag:h0QPNm4VRPZQ5aQOsYEffw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
