apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak-instances
resources:
  - ../../base
#  - sealed.yaml
patches:
  - target:
      kind: KeycloakRealmImport
      name: havenplus-realm-import
    patch: |
      - op: replace
        path: /spec/realm/clients/1/redirectUris/0
        value: "https://set-in-overlay/login/generic_oauth"
