apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-init

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-init
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["openbao-init-credentials"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-init
subjects:
  - kind: ServiceAccount
    name: openbao-init
    namespace: openbao
roleRef:
  kind: Role
  name: openbao-init
  apiGroup: rbac.authorization.k8s.io
