apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-rolebinding
subjects:
- kind: ServiceAccount
  name: garage-postconfig
  namespace: garage
roleRef:
  kind: Role
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-postconfig

---
apiVersion: batch/v1
kind: Job
metadata:
  name: garage-postconfig
spec:
  template:
    spec:
      serviceAccountName: garage-postconfig
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postconfig
        image: bitnamilegacy/kubectl:1.33.4
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Configure cluster layout
            NODE_ID=$(kubectl exec garage-0 -c garage -- /garage node id -q)
            echo "Node ID: $NODE_ID"
            kubectl exec garage-0 -c garage -- /garage layout assign -z havenpc -c 50GB "${NODE_ID}"
            kubectl exec garage-0 -c garage -- /garage layout apply --version 1

            # Import static access key for local env
            kubectl exec garage-0 -c garage -- /garage key import -n havenpc-key "$S3_ACCESS_KEY_ID" "$S3_SECRET_ACCESS_KEY" --yes

            # Create buckets
            kubectl exec garage-0 -c garage -- /garage bucket create velero
            kubectl exec garage-0 -c garage -- /garage bucket create loki-chunks
            kubectl exec garage-0 -c garage -- /garage bucket create loki-ruler
            kubectl exec garage-0 -c garage -- /garage bucket create loki-admin
            kubectl exec garage-0 -c garage -- /garage bucket create mimir-blocks
            kubectl exec garage-0 -c garage -- /garage bucket create mimir-alertmanager
            kubectl exec garage-0 -c garage -- /garage bucket create mimir-ruler

            # Set bucket permissions
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner velero --key havenpc-key
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner loki-admin --key havenpc-key
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner loki-chunks --key havenpc-key
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner loki-ruler --key havenpc-key
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner mimir-blocks --key havenpc-key
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner mimir-alertmanager --key havenpc-key
            kubectl exec garage-0 -c garage -- /garage bucket allow --read --write --owner mimir-ruler --key havenpc-key

        envFrom:
          - secretRef:
              name: s3-credentials
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      restartPolicy: Never
  backoffLimit: 1
