apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    namespace: garage
type: Opaque
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:1Jsa1vtEKbLSbj/Gwx2QDmfkZByih0XMRqQ=,iv:cI+aDIhKvloW8l9JbL/cQN6zIGQo9UQLeaEHZapQJos=,tag:qIRcPHx+k3pyrpVTpzmHCw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:F/UbJfD8ADnu6DKSRnlUBfr0pqkl5/2K6jcSGmSuQ6n/Wpfk0qggbN4O5SrqPtrtyuOAzlZ9ZsRHpjftjRDRgQ==,iv:POAT1PAW2E+m2MdBqDguWHXcEanS9+wqa98NHOnuEec=,tag:OXtPRnTh8iX9yjVJdQCCqw==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU3pUYTF6SFpwRlNUam9H
            eC9ReXZvbmZuT0ZKZi9zbXUvRTdKSldZODBNCjltNmVXZEhtd25CUkhOQWtjQy9l
            V1BBaEsxNEh1Yk96Vi9oTEF2UVlqakUKLS0tIDBsM0JjRTNiZ2JYSXI0enJjT21K
            aEJkMStNbnQxaldXcjlzQ2dFbG0ybUUKllJV1q49kiHh42Yf8tFAtss3e1nCOCkL
            BVJcy8h/F7uZZBOktz1M9IbHmqmGjF4Eh4df9a0+uAHqW/ggbA436g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T07:55:04Z"
    mac: ENC[AES256_GCM,data:gcEERi81HIEOI2CP3Wlk9qKB1M99b5cppTmHAzeTSQnKR3CI1g+I7eT5I9Ki/nXjtOOcy6vm8Hd6z7OVEntIqwKnq3rO+T/E+84DsPMsKcU6pL5B9A19d6xD6SSmWT/PAtESACZgYRwtf3KQp24CJVZNu3RoA9UbvMcPEH38VXY=,iv:QfzebwIAUDbXQzb7Ey3yJS4sZFr3aGxfSMjgv1mhs0M=,tag:j+Em3YZAs+zqiEklhppIjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
