apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chart:
    spec:
      chart: openbao
      version: "0.29.4"
      sourceRef:
        kind: HelmRepository
        name: openbao
      interval: 12h
  values:
    server:
      statefulSet:
        securityContext:
          container:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
