apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=10
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s      
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"
# Multi-Tenancy is disabled for now, as it requires a bit more work to get it functional.
# patches:
#   - patch: |
#       - op: add
#         path: /spec/template/spec/containers/0/args/0
#         value: --no-cross-namespace-refs=true
#     target:
#       kind: Deployment
#       name: "(kustomize-controller|helm-controller|notification-controller|image-reflector-controller|image-automation-controller)"
#   - patch: |
#       - op: add
#         path: /spec/template/spec/containers/0/args/-
#         value: --no-remote-bases=true
#     target:
#       kind: Deployment
#       name: "kustomize-controller"
#   - patch: |
#       - op: add
#         path: /spec/template/spec/containers/0/args/0
#         value: --default-service-account=default
#     target:
#       kind: Deployment
#       name: "(kustomize-controller|helm-controller)"
#   - patch: |
#       - op: add
#         path: /spec/serviceAccountName
#         value: kustomize-controller
#     target:
#       kind: Kustomization
#       name: "flux-system"
