# ZGW-credentials voor de koppeling Open Zaak <-> Open Notificaties én de
# OIDC-clientsecrets (Keycloak realm havenplus). Zie realm-patch.yaml in de fork.
# Naam bewust niet "<app>-config-secrets": die beheert de Helm-chart zelf.
apiVersion: v1
kind: Secret
metadata:
    name: openzaak-koppeling
    namespace: openzaak
type: Opaque
stringData:
    secret_openzaak: ENC[AES256_GCM,data:VaZT8wQe4BNZtYw0YgqC7Bj2g8sUZm7b6X668Tzpob3vx2bQrCwXJTKGuuppcxNM,iv:jo2HRJfpxy98b++WTub2TDYMqQMKJcH9C6h1wcloay4=,tag:mWgMysQ2sJU2HMJ3HkNUsA==,type:str]
    secret_opennotificaties: ENC[AES256_GCM,data:6f25M0CZRjhJPgXgiWoiORAaFkqOlS7yZn05PXJOGBfnop5A7VSw44IMGJe4lFCf,iv:gWj8KkMV9qc13byypHgNFzmoXGLsD7FK5oNpagxPVeY=,tag:C9lSdfnecnGIMDlW0p7dQA==,type:str]
    oidc_client_secret: ENC[AES256_GCM,data:bz7QaL2gH8w52LKcBQ5sNuKAR/61otUvBs047cU4e6JaqlbVlgTAEQ==,iv:VKOR5OwgAbAxL2MYYPXHQLsCg71PSWAbhB6CKkiUQ6s=,tag:NnAUc3y1V18ZXyZvveKHsQ==,type:str]
    secret_loket: ENC[AES256_GCM,data:wYdUXtIlPupKVFTCea3nIxV8A0R1q/B8o6RRvVFDUIcD3gg2RboTUxxQJDTBWzGsqrrkTxXepZ063as2/UKr4Q==,iv:j3EVV48YvuMSrApeuq27GCVWNwieeCRds8S02T2h1xA=,tag:X2EwBGyqxPrtwJedzyDPsA==,type:str]
    secret_behandeling: ENC[AES256_GCM,data:f4mueKFgybnrdlSdJf2T2DMIBUvCPTlSy0QFIpzGEKX+vAHSxx1r+xlul/ee3s8EjD1q7zprDWCPevobpFF7SQ==,iv:/uUS/fq8TNQNjdRumWfyzbZ8PeLncF99Ye5TvXFJbjE=,tag:WtxbzPJBnVmDFdFwGx9sBg==,type:str]
    secret_forensisch: ENC[AES256_GCM,data:LVREUpmIag7hS8QOWOTELboqHDwB3Z/GXeDq0lmLplm0KKJ3Vpo7y2/Y6a8pBXgFKHwPGPryIHUYnmsEw5DZfw==,iv:FH8JCOQdYciTtI97OQoMLX0RmaaTkeRWXYzX06celoA=,tag:ORPwSJu1O3SRTt7t7zHJ6w==,type:str]
    werkplek_oidc_secret: ENC[AES256_GCM,data:u+SJzC8pWsX2cI2QI2LrV7+tNb0yoqsZidAUAfrhrJqO2nJM23nAtvaqx7Tz/DqEZoCToJ3uhghAKMMV7BtOEg==,iv:V+X0314Cl9UqJyMVAZW3UqPod9Vx26bIxS7NLCDMzfU=,tag:JBy39nGDGlbafKGln8IiZQ==,type:str]
    werkplek_flask_secret: ENC[AES256_GCM,data:kHUEkScxBjvVYy+7PWzh1Fiv0sF0vb/Isvg++FRfnazLrK82QdEIcR8uj+4dVCYfAaPa2YVWSaDzXHwCFWNKGQ==,iv:2SKbe89n+DNUrbETQB+B2Jkx/jMUJ7INweUUMR3QSXE=,tag:n7AokCLuPwBimuszVamSYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTmtIcmZzZ3J1YmNxMnFk
            eTJTeHRLWElXZ3RkdE05bC9ZSmZUdHJJK1dVCm5JM0lva2dlSjVyckNMK2kyOERv
            NDd5NHh0QXo4VnNkaUV1RGlKeGJLZG8KLS0tICtyd01vQjVCNlJ1TnphTEpqTXkx
            cFlEcFVvVWUxdks2ZGV4b0NEWGxxZEUKbUkRd4wCZzgcgZhobIJqja01SGsYwLAF
            Fs7pkzUHVAcxwrwzq/yx3NyfrLgBefLYHA9tjWlEtvd0FUA3iCTxAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T15:57:59Z"
    mac: ENC[AES256_GCM,data:e7PqWUIQf0jNWp0Xi8a/XyjxsPdnuo+W0ZyY0RgPFcmZBI2oHZOVlwPfSmH5vHue5m/AfiUTYhHiC3tFyecYzL9MNLRid3Md8949YhBh/RTGKOCplTYsqhcKWkyExNLtE2KXvs3BvlRX/ze++F/gioXGyEK+yneS52PaYhEq4jc=,iv:fR4Gj4BXVivBLCqfYLX+FalGYPmRXOuEVt9Unf/Sp+w=,tag:gp0hV97MlxBtEIoz3S5ScA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: opennotificaties-koppeling
    namespace: openzaak
type: Opaque
stringData:
    secret_openzaak: ENC[AES256_GCM,data:LwktOwrcHgdAA6gN/tyap84pPVdM8+km/8Mpf8Ym7gK0OSj4yZrDqupPLDEpHxwP,iv:AQ3dSaxs6zy0DaweRPjBseojuAOqtciyB8uOLDT8r7g=,tag:2/bHBomxSTWIm2M1vezPKg==,type:str]
    secret_opennotificaties: ENC[AES256_GCM,data:LPcMNp0QHhB1VnSBJ92KT53QqNTMkYCubgdTPtm/+MFwv8jV6fsR9+p+crpFKEFh,iv:8W7EbxCYzCSTfuvRA6QiPtSsYm7VnK7Pv2qH19MloTE=,tag:cnoWe8Z8FZtv6bJs+uudEw==,type:str]
    oidc_client_secret: ENC[AES256_GCM,data:xIxFk85Ek3waI8zWoJSaxiXGiYN3mHjBS82GF2rLj39qs8dRn8MwHw==,iv:AEaxpHleI0aJ+hfhwAt9HVAWKka7vorKQr1v59kt/dI=,tag:AVM1N5/nMSe7UBY0csVE2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTmtIcmZzZ3J1YmNxMnFk
            eTJTeHRLWElXZ3RkdE05bC9ZSmZUdHJJK1dVCm5JM0lva2dlSjVyckNMK2kyOERv
            NDd5NHh0QXo4VnNkaUV1RGlKeGJLZG8KLS0tICtyd01vQjVCNlJ1TnphTEpqTXkx
            cFlEcFVvVWUxdks2ZGV4b0NEWGxxZEUKbUkRd4wCZzgcgZhobIJqja01SGsYwLAF
            Fs7pkzUHVAcxwrwzq/yx3NyfrLgBefLYHA9tjWlEtvd0FUA3iCTxAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T15:57:59Z"
    mac: ENC[AES256_GCM,data:e7PqWUIQf0jNWp0Xi8a/XyjxsPdnuo+W0ZyY0RgPFcmZBI2oHZOVlwPfSmH5vHue5m/AfiUTYhHiC3tFyecYzL9MNLRid3Md8949YhBh/RTGKOCplTYsqhcKWkyExNLtE2KXvs3BvlRX/ze++F/gioXGyEK+yneS52PaYhEq4jc=,iv:fR4Gj4BXVivBLCqfYLX+FalGYPmRXOuEVt9Unf/Sp+w=,tag:gp0hV97MlxBtEIoz3S5ScA==,type:str]
    version: 3.13.3
