# ZGW-credentials voor de koppeling Open Zaak <-> Open Notificaties én de
# OIDC-clientsecrets (Keycloak realm havenplus). Zie realm-patch.yaml in de fork.
# Naam bewust niet "<app>-config-secrets": die beheert de Helm-chart zelf.
apiVersion: v1
kind: Secret
metadata:
    name: openzaak-koppeling
    namespace: openzaak
type: Opaque
stringData:
    secret_openzaak: ENC[AES256_GCM,data:c+aCirj6nRYIV9nh1Ya3f3Bkh1jaEtD4zrGQEOzMKGW3/ZH1x2IYHDXnycypdxdK,iv:nCqNF7TmM/yVko81eDcqmy9X+U3p8ZLJ6cxj7o+ZAZc=,tag:6YwK7aqMJrX8jt1pZUe4Ng==,type:str]
    secret_opennotificaties: ENC[AES256_GCM,data:2Pgsjmeikn7v5njg8PUSyFehK6g8vtxlhr+VXr4x7ETt16IXuwU8XJ1LtAgxzQGC,iv:FN9a8Fnp/7oL3yIxR/yeB8KWfn4kmuq8W/Se3I+4uVU=,tag:Qk9UJMl4CykiQD1m2yegsQ==,type:str]
    oidc_client_secret: ENC[AES256_GCM,data:4ktrvwLlpYOdx9eQb9bnLWdkPqtXhz7W7izkJG9z2/EXtvTYSc9aYQ==,iv:Vph8762aOHSlUGeKvuMtXwGtx49FaSNSoOLufJxoF9A=,tag:U3Nc1UZoAMpr/KXF/bZwcQ==,type:str]
    secret_loket: ENC[AES256_GCM,data:sSm9RSCCVNL1MN75EshFUuuY3RqrxZDyikTnsa+xMQ4lSyxU8kXMlB4yhFWksolLcZ3l/6pMsudX89cfE365hg==,iv:HKtj/rKkx4fGFJnQRM6OJFGIKjfWg2o4fKsjIxbLL7A=,tag:rtWz2kFOOeC4sKO+U2ft8A==,type:str]
    secret_behandeling: ENC[AES256_GCM,data:kdUQCP3yQdvETJUlRuRA/h7xNqwBB4oqoxniO51Dgtk6RAT6kLntLsuBKS2ty2qR4G9s4+ePy5JuMHhVKyLqHw==,iv:zIwiZAqFi9pRiyzOn1hLlJ2JDOFkI8F31pglzvRI5ck=,tag:RNeQiYMKsCj+2ePtRJSmNQ==,type:str]
    secret_forensisch: ENC[AES256_GCM,data:fiAuAQdp0gT+acJmfR1NhVKPHYqz3mFAXxb8nTkYPkc6TwFe05axshMEToMBM3lp3pkHzZrjvwJXqlQoEUvdPQ==,iv:GwIqP2jnQRZQaMhyWMf+oHTsCS5oaLRnV8T9tK9QrAU=,tag:MutLyXfrBUfnMC18wUlfLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTEc1b21rbVhldTY0Z1p0
            dlByUlZ0WkxWSTVIVjFnTzhyOGJKUk9mUGlnClNpSWNEamF1NEJIOEFpb005R1BB
            M3U5eUgyek9aU2FHOU1FRlNwSG5ONzAKLS0tICtaaWxFMGZqMzlCb1M3Mk1hMkN5
            M0F1US8yRU54TFRielc5YklZN1VKTFkKA9WQ49dSXC9YZCr+gmo+kbEDZi+jcfsm
            StoAHTAUSaHku5s48G8+UTc9ZZ/IDsAe+PDMrqeNEd464jXuGmSbdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:23:33Z"
    mac: ENC[AES256_GCM,data:Vib0fvP81g//knQYrfINbeUimjnN+2KtdMaBCCwAD7af5OEp2VkbgGQJOqmvF1IUI6Ukskj5GCkHCREnIgWE3KlaW6YUUI6QeUg1Xls7x2F7r6AfGn3yWq2e3GvKrIRChqBTCpSpLFLLPLD7eKnoTcsAHBboMsZBsAzgak5w3sg=,iv:bVZVCNgcagfbOjPhkld5q+o297q+Xa+NWrlQ03OP0Qk=,tag:C6Z/WXzEq6h0YHDyClevGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: opennotificaties-koppeling
    namespace: openzaak
type: Opaque
stringData:
    secret_openzaak: ENC[AES256_GCM,data:jZRlSGAM+zI2XLaIcefTYzNqjxTKWw0nDLboKOFFzegTSK7PaPqxJJCxg4MFleOy,iv:kSF9iZF6+HfAg2QrqIOP1Jk/ER6drjWdyc3a58HrwqQ=,tag:CvRcAv5IIGyzzBKmSs9D9g==,type:str]
    secret_opennotificaties: ENC[AES256_GCM,data:1pucTSy7kztaW0nvslL2gwQ2mlH/9yX7s10mmJTWLClrUR2gtge/sbWzyu8ARc5W,iv:xCXM6sVgaENQmupwgcYVITqAduW2ufJSFJTrAq/0PP0=,tag:iBqZ/X2bx4u+2gzJppPnxw==,type:str]
    oidc_client_secret: ENC[AES256_GCM,data:JRDmo7LsRDdyV4x0KSn4VQ3bAqZokDSRZ7/Gwhl9qiWFme2u4GVsKQ==,iv:81cYjbwlRF0z9I/XLp5MT2sAoAAdPFWSnuYz1S6EjiE=,tag:gJifexOiHBeXIyp3iBH4Cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTEc1b21rbVhldTY0Z1p0
            dlByUlZ0WkxWSTVIVjFnTzhyOGJKUk9mUGlnClNpSWNEamF1NEJIOEFpb005R1BB
            M3U5eUgyek9aU2FHOU1FRlNwSG5ONzAKLS0tICtaaWxFMGZqMzlCb1M3Mk1hMkN5
            M0F1US8yRU54TFRielc5YklZN1VKTFkKA9WQ49dSXC9YZCr+gmo+kbEDZi+jcfsm
            StoAHTAUSaHku5s48G8+UTc9ZZ/IDsAe+PDMrqeNEd464jXuGmSbdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:23:33Z"
    mac: ENC[AES256_GCM,data:Vib0fvP81g//knQYrfINbeUimjnN+2KtdMaBCCwAD7af5OEp2VkbgGQJOqmvF1IUI6Ukskj5GCkHCREnIgWE3KlaW6YUUI6QeUg1Xls7x2F7r6AfGn3yWq2e3GvKrIRChqBTCpSpLFLLPLD7eKnoTcsAHBboMsZBsAzgak5w3sg=,iv:bVZVCNgcagfbOjPhkld5q+o297q+Xa+NWrlQ03OP0Qk=,tag:C6Z/WXzEq6h0YHDyClevGg==,type:str]
    version: 3.13.3
