# CNPG-bootstrapsecrets (basic-auth) + Helm-values met geheimen; beide
# versleuteld met de age-sleutel van havenpc (Flux decryption).
apiVersion: v1
kind: Secret
metadata:
    name: openzaak-db
    namespace: openzaak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:pPW8H6W3ue8=,iv:GVKGTMv3jql/N2lglxQSXbai7SffvNN+bDDwn7d4OJg=,tag:F1cPtJeSF6rr7yEvHHsL+Q==,type:str]
    password: ENC[AES256_GCM,data:SwvggDZjPlJzZp9kWjMs4SikKZS7GnpyUrRn5Q==,iv:ONsCao037T7zKBQcbH5WLWETAXVaKpcAUSYLluT3fD4=,tag:gGCMytRUMuofj7a2X+yXRg==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMmdhWWI3c2l6QnN3Wk13
            TlEzV1M0RDdiZ0tvQ1B0UzBNM3ZlTWlNM1VvCnNJeHFDYnhwamRwd3N2SUxkcXFa
            RWZ6TmxXbzR1TDVGZUI1K3l4WERYb00KLS0tIFFXZU9YdzBDc21pQ0Z1SGhranRo
            aE51dHpSRUFXWVV1OTVNbG9BdEJEUkUKu592nheICO7MS27OlKiKYPYQUdRd6Uhp
            jRCrDMSira3HkhmPypqhWX+wfRagyZWcjSpR3JluWxxLEiUz32dHSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T09:13:33Z"
    mac: ENC[AES256_GCM,data:sGfhtHJgLcWF3YLocW48ZZu97LrotgisRYquWal8mfJzAEwQwz8OfXfEUdvZdQd4MADiwKFPNpJ+6JST5GSclCY7JJfUgjS9gY4xiQf/9sGX80tq78G3vT2R/zshaTGqQCZ1ZV+xh5vPV5OnoybnFImgLMcwBYrWkmk4fDcWg5c=,iv:oAWUhaaQ2MxyNDsIhulSFq7RiD2pQpixY6MqQ+u8KxY=,tag:BsjEYXZI6jAqQd28jmhflA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: opennotificaties-db
    namespace: openzaak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XdXmZqlaRU96XfHLW1Dcbg==,iv:QHpiP/A3U3dMryhdNPV4hVUmFsun7JJ+2BuJ1fGkz/4=,tag:dZQv+MHBDtb7xXSQzUMH5w==,type:str]
    password: ENC[AES256_GCM,data:3j3yYKQd3NziNx4ey6Rlv0hTKQ/vAvNFKTducA==,iv:mYLiz2Njh8J6NBrOEVjJT+PHS1tnqvJ8BH4aRzTR+68=,tag:0Pizb4pZOiimzNG81O3C8w==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMmdhWWI3c2l6QnN3Wk13
            TlEzV1M0RDdiZ0tvQ1B0UzBNM3ZlTWlNM1VvCnNJeHFDYnhwamRwd3N2SUxkcXFa
            RWZ6TmxXbzR1TDVGZUI1K3l4WERYb00KLS0tIFFXZU9YdzBDc21pQ0Z1SGhranRo
            aE51dHpSRUFXWVV1OTVNbG9BdEJEUkUKu592nheICO7MS27OlKiKYPYQUdRd6Uhp
            jRCrDMSira3HkhmPypqhWX+wfRagyZWcjSpR3JluWxxLEiUz32dHSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T09:13:33Z"
    mac: ENC[AES256_GCM,data:sGfhtHJgLcWF3YLocW48ZZu97LrotgisRYquWal8mfJzAEwQwz8OfXfEUdvZdQd4MADiwKFPNpJ+6JST5GSclCY7JJfUgjS9gY4xiQf/9sGX80tq78G3vT2R/zshaTGqQCZ1ZV+xh5vPV5OnoybnFImgLMcwBYrWkmk4fDcWg5c=,iv:oAWUhaaQ2MxyNDsIhulSFq7RiD2pQpixY6MqQ+u8KxY=,tag:BsjEYXZI6jAqQd28jmhflA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: openzaak-values
    namespace: openzaak
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:N+f0Cvca4If2UETViPvoB0jUMmdObwE82ZaAQ2QqtT+3B3gsN+sGHJtKSm5P7dCNvzmGX6G6XrUHEqLKLHIft3hbs2sA0bpSQpWzuU57v6X2TdrtMpAp2AQjW3EU1xC6RYbHhb5Bk/d/mIusaYtqN8BR/nDJBKN+Y9Q/BY/CXZLFt6n63fh7a2xzYvRDZanlooYy/gi/nwWhGI/ZtiT7ve9Qyp8DzcgCGCjEKYkyH9CL053OUuE75cJhEwg+xYThfv46InR3ojfMRg4xmtVPiw5mQnzbYyqyZMKxtgSOpF/q3Yim+SZ2aR1UZiPNMg==,iv:DrePJdqYPgpLgQbjgJdmi6/P2Z9fe14a0WL70OLVJH0=,tag:I/twyBHZB/Bjl4mL9JbF1g==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMmdhWWI3c2l6QnN3Wk13
            TlEzV1M0RDdiZ0tvQ1B0UzBNM3ZlTWlNM1VvCnNJeHFDYnhwamRwd3N2SUxkcXFa
            RWZ6TmxXbzR1TDVGZUI1K3l4WERYb00KLS0tIFFXZU9YdzBDc21pQ0Z1SGhranRo
            aE51dHpSRUFXWVV1OTVNbG9BdEJEUkUKu592nheICO7MS27OlKiKYPYQUdRd6Uhp
            jRCrDMSira3HkhmPypqhWX+wfRagyZWcjSpR3JluWxxLEiUz32dHSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T09:13:33Z"
    mac: ENC[AES256_GCM,data:sGfhtHJgLcWF3YLocW48ZZu97LrotgisRYquWal8mfJzAEwQwz8OfXfEUdvZdQd4MADiwKFPNpJ+6JST5GSclCY7JJfUgjS9gY4xiQf/9sGX80tq78G3vT2R/zshaTGqQCZ1ZV+xh5vPV5OnoybnFImgLMcwBYrWkmk4fDcWg5c=,iv:oAWUhaaQ2MxyNDsIhulSFq7RiD2pQpixY6MqQ+u8KxY=,tag:BsjEYXZI6jAqQd28jmhflA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: opennotificaties-values
    namespace: openzaak
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:T2xlWGEPo+JMC+pEHFig0tSSIom7+wsdG0YV7sUveXJQ3dCHOsn+7aA6cayjs6uAMR3bQf52bYvCLbsFFoX1ddcRybOCwfUt3t1NuYURxrp7sB4JoXaSQTC4NdJ5l/76qfI8vcpjxMznesMs4wSnw3ijsM8paETabTPZMmwNHEwMrdnbpYU8glhZ73KLj4z498kz+KRtJ7UQJUxgrdYNAk3nS/sxTqwosYnXanFkdqytQ3JXXrFItGO+UF88eEK1sLJIfelN5KbgpQcEo9bzMPREjB+iYtnCmA8E3uyjjaRuYLrQqKWUQ2aca2s6,iv:k2UkqpJ6NtlunJDx8U2cb1zE6pNg4/hTmsoB1Nqh2qI=,tag:7e20118sqEZXGC+LaUDu4g==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMmdhWWI3c2l6QnN3Wk13
            TlEzV1M0RDdiZ0tvQ1B0UzBNM3ZlTWlNM1VvCnNJeHFDYnhwamRwd3N2SUxkcXFa
            RWZ6TmxXbzR1TDVGZUI1K3l4WERYb00KLS0tIFFXZU9YdzBDc21pQ0Z1SGhranRo
            aE51dHpSRUFXWVV1OTVNbG9BdEJEUkUKu592nheICO7MS27OlKiKYPYQUdRd6Uhp
            jRCrDMSira3HkhmPypqhWX+wfRagyZWcjSpR3JluWxxLEiUz32dHSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T09:13:33Z"
    mac: ENC[AES256_GCM,data:sGfhtHJgLcWF3YLocW48ZZu97LrotgisRYquWal8mfJzAEwQwz8OfXfEUdvZdQd4MADiwKFPNpJ+6JST5GSclCY7JJfUgjS9gY4xiQf/9sGX80tq78G3vT2R/zshaTGqQCZ1ZV+xh5vPV5OnoybnFImgLMcwBYrWkmk4fDcWg5c=,iv:oAWUhaaQ2MxyNDsIhulSFq7RiD2pQpixY6MqQ+u8KxY=,tag:BsjEYXZI6jAqQd28jmhflA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
