# CNPG-bootstrapsecrets (basic-auth) + Helm-values met geheimen; beide
# versleuteld met de age-sleutel van havenpc (Flux decryption).
apiVersion: v1
kind: Secret
metadata:
    name: openzaak-db
    namespace: openzaak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:SygPPigQwOM=,iv:0/J2y5+AkiYLh/RWhwExbDGLBMlVI9prcKSQ49LkxKU=,tag:Ziq9kbXSh2f1L5xx/za/Mw==,type:str]
    password: ENC[AES256_GCM,data:x4pVQf8UrdZoDDgv19xaVvisT3va3eFIbQ+19g==,iv:e8NHN52j62PI8x57bOBlgz7q3gTpLMMNWSLysMKu4G4=,tag:HUCxbj9maPiEVXbGuRZAlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnVubTdGSUoyTkJLek11
            WVQ1K250emcwWFJYVlVNTmVWb2YrUnFJaHhnCks2ZnVFM0k5a1NWbVBGNHlLL011
            VXZoR3lsVmVvaStWTk1EeTBnaG52SEUKLS0tIDdwWGN2QkEvSUcrTTVRc3NEUmFO
            YUl6OEtaNVBYTHgvNmhiU3p3Q2s1ZHcKQIUGVzhkGwMv/WxqB2bHZIck8zoaxu3i
            ZcaWGe0bBM2/3WeymmgONG9CAESorMJGgshYbilBvcTVt0ZA+Oka+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T08:11:33Z"
    mac: ENC[AES256_GCM,data:ptEz69o1onQ9aldSUmCznUdYsO77BHPWW9PFMu6EQCoV6gNPRRorDHSPVVQpUChB3XubGCw8ngR2lMi84YijxSxo8Y5VafExo8SgyLPb+P6SIQV7YvJA0TwZCDzn02SCmhYPdU6GSmCyxews4LNCMROZZPrlTChuLHwgrWEEBdM=,iv:2xH31L3tinhpxz7Cvm+57516WsS5KdFPiJfjzuGrlz4=,tag:lnSho4zvdSX1+YKfU1/08Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: opennotificaties-db
    namespace: openzaak
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:peIIyK9ejT4o2Qex0+ig+A==,iv:qVMMQYPY3zd5zNPyzWGb7FE7liQjT5B+GndKPliCOfc=,tag:QraZEi/y4SF/354iU+Tsmw==,type:str]
    password: ENC[AES256_GCM,data:T+vxqYTMtj2IZt8Ge6pH8VZdFKN/VW/+gw9DcA==,iv:EfUHMnEIGGmdZusHZjCbvwxT6L+uXA3mPoF1BzHr/Zo=,tag:MpZVgEo8zVjRVCD02Qytbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnVubTdGSUoyTkJLek11
            WVQ1K250emcwWFJYVlVNTmVWb2YrUnFJaHhnCks2ZnVFM0k5a1NWbVBGNHlLL011
            VXZoR3lsVmVvaStWTk1EeTBnaG52SEUKLS0tIDdwWGN2QkEvSUcrTTVRc3NEUmFO
            YUl6OEtaNVBYTHgvNmhiU3p3Q2s1ZHcKQIUGVzhkGwMv/WxqB2bHZIck8zoaxu3i
            ZcaWGe0bBM2/3WeymmgONG9CAESorMJGgshYbilBvcTVt0ZA+Oka+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T08:11:33Z"
    mac: ENC[AES256_GCM,data:ptEz69o1onQ9aldSUmCznUdYsO77BHPWW9PFMu6EQCoV6gNPRRorDHSPVVQpUChB3XubGCw8ngR2lMi84YijxSxo8Y5VafExo8SgyLPb+P6SIQV7YvJA0TwZCDzn02SCmhYPdU6GSmCyxews4LNCMROZZPrlTChuLHwgrWEEBdM=,iv:2xH31L3tinhpxz7Cvm+57516WsS5KdFPiJfjzuGrlz4=,tag:lnSho4zvdSX1+YKfU1/08Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: openzaak-values
    namespace: openzaak
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:q4Q56354yiMcEmB3Kl2/H1yQjI/fcxnWdEFOu2EbZb8Z+JGaqGFdXp9PyvnFGyE3ik3VO3XSBMTvgLO1/JSgEFElbgthgJjlpK4Dfs9K0HoPHEFaxmgpsPG5rg94xQ58GImwHq3OB0sY8dmNCv2w0dDhVwmVw49QeTKc2xeAWhcA68PpZmcaM4PBxezgzlf885wS9NMZHV9IA2tA04lrLg+aRCS/W89is7i1E97YBYidHosLS3AUFhX8AO7U04bTOfWifS1ULm3leqpGpOuBWgkeLJr1quwCwW3eu4uQ7NiC+ZNOH5dq9TMPBChu85fFb9EUjRQ=,iv:e3wc/kWc4D54sx/1Ae4FEZ+Wc5ZqcjnoVs8CjCevu84=,tag:Jhxw+/+RBCBqjZRJypBoBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnVubTdGSUoyTkJLek11
            WVQ1K250emcwWFJYVlVNTmVWb2YrUnFJaHhnCks2ZnVFM0k5a1NWbVBGNHlLL011
            VXZoR3lsVmVvaStWTk1EeTBnaG52SEUKLS0tIDdwWGN2QkEvSUcrTTVRc3NEUmFO
            YUl6OEtaNVBYTHgvNmhiU3p3Q2s1ZHcKQIUGVzhkGwMv/WxqB2bHZIck8zoaxu3i
            ZcaWGe0bBM2/3WeymmgONG9CAESorMJGgshYbilBvcTVt0ZA+Oka+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T08:11:33Z"
    mac: ENC[AES256_GCM,data:ptEz69o1onQ9aldSUmCznUdYsO77BHPWW9PFMu6EQCoV6gNPRRorDHSPVVQpUChB3XubGCw8ngR2lMi84YijxSxo8Y5VafExo8SgyLPb+P6SIQV7YvJA0TwZCDzn02SCmhYPdU6GSmCyxews4LNCMROZZPrlTChuLHwgrWEEBdM=,iv:2xH31L3tinhpxz7Cvm+57516WsS5KdFPiJfjzuGrlz4=,tag:lnSho4zvdSX1+YKfU1/08Q==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: opennotificaties-values
    namespace: openzaak
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:VeYIQVXfaWKLTjid9BS2OUf4RuNv1oP/19PwVvwsHDPP23gZXQ78rnu6YxbpwbcDb2ZTpVmzbQFNesxEpwx3iRvHhQ1osvOdB7OiH3jyy8Z0ZpFd5DI0RX5Yckaw7qkaW3xYDfAektZBJIg2uKqv3D6PeTIDzMVfTHBm8pfF0SlLRqnd4cXR33uzAbgen+aos9L9Ea1Ohd8Y4dEAa0w1RqogU13PhmRr7JRSX/9TQyTgZaB/pA4+pdhPvXmqRTKvLgzbWtJW1IEBt3D+Y9tOeOivnyWyogGag7LZRetywlrwCDO1YKaCniAea4OQBeJLs+S1Ng==,iv:CNF2dbzz3kv2bOKnL3IXmxdtL9znLVojr09WlR+XdXw=,tag:eqEEK/QPhKhHBCZsgYAVrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnVubTdGSUoyTkJLek11
            WVQ1K250emcwWFJYVlVNTmVWb2YrUnFJaHhnCks2ZnVFM0k5a1NWbVBGNHlLL011
            VXZoR3lsVmVvaStWTk1EeTBnaG52SEUKLS0tIDdwWGN2QkEvSUcrTTVRc3NEUmFO
            YUl6OEtaNVBYTHgvNmhiU3p3Q2s1ZHcKQIUGVzhkGwMv/WxqB2bHZIck8zoaxu3i
            ZcaWGe0bBM2/3WeymmgONG9CAESorMJGgshYbilBvcTVt0ZA+Oka+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T08:11:33Z"
    mac: ENC[AES256_GCM,data:ptEz69o1onQ9aldSUmCznUdYsO77BHPWW9PFMu6EQCoV6gNPRRorDHSPVVQpUChB3XubGCw8ngR2lMi84YijxSxo8Y5VafExo8SgyLPb+P6SIQV7YvJA0TwZCDzn02SCmhYPdU6GSmCyxews4LNCMROZZPrlTChuLHwgrWEEBdM=,iv:2xH31L3tinhpxz7Cvm+57516WsS5KdFPiJfjzuGrlz4=,tag:lnSho4zvdSX1+YKfU1/08Q==,type:str]
    version: 3.13.3
