apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    server:
      root_url: "set-in-overlay"
      enable_gzip: "true"
    analytics:
      reporting_enabled: "false"
    security:
      cookie_secure: "true"
      cookie_samesite: "strict"
      content_security_policy: "true"
    auth:
      login_cookie_name: "__Host-grafana_session"
    users:
      allow_sign_up: "false"
      viewers_can_edit: "true"
    auth.generic_oauth:
      enabled: "true"
      name: "Keycloak"
      client_id: "grafana"
      use_pkce: "true"
      scopes: "openid email profile"
      auth_url:  "https://set-in-overlay/realms/havenplus/protocol/openid-connect/auth"
      token_url: "https://set-in-overlay/realms/havenplus/protocol/openid-connect/token"
      api_url:   "https://set-in-overlay/realms/havenplus/protocol/openid-connect/userinfo"
      groups_attribute_path: "groups"
      allow_assign_grafana_admin: "true"
      role_attribute_path: >-
        contains(groups[*], 'k8s-admins') && 'GrafanaAdmin' ||
        contains(groups[*], 'k8s-developers') && 'Editor' || 'Viewer'
  httpRoute:
    spec:
      parentRefs:
        - { name: public-gateway, namespace: istio-gateway }
      hostnames: [ set-in-overlay ]
      rules:
        - backendRefs:
            - { name: grafana-service, port: 3000 }
