apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: designate-certmanager-webhook
spec:
  interval: 30m
  driftDetection:
    mode: disabled
  install:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy: 
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: designate-certmanager-webhook
  values:
    replicaCount: 1
    credentialsSecret: cloud-credentials
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
