apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fieldlab-platform-dienstverlening-nl-wildcard
spec:
  secretName: fieldlab-platform-dienstverlening-nl-wildcard-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - "*.fieldlab.platform-dienstverlening.nl"
