# CONTROLLER
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-controller
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/kyverno/controller/overlays/lab-clusters/cyso-pdv
  prune: false
  wait: true
  dependsOn:
    - name: cluster-resources

---
# POLICIES
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/kyverno/policies/overlays/lab-clusters/cyso-pdv
  prune: false
  wait: true
  dependsOn:
    - name: cluster-resources
    - name: kyverno-controller

---
# POLICIY-REPORTER
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policy-reporter
  namespace: flux-system
spec:
  interval: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/kyverno/policy-reporter/overlays/lab-clusters/cyso-pdv
  prune: false
  wait: true
  dependsOn:
    - name: kyverno-policies
