apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencost
resources:
  - ../../base
configMapGenerator:
  - name: opencost-oauth2-proxy-config
    options:
      disableNameSuffixHash: true
    literals:
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://set-in-overlay/realms/havenplus
      - OAUTH2_PROXY_REDIRECT_URL=https://set-in-overlay/oauth2/callback
      - OAUTH2_PROXY_COOKIE_DOMAINS=set-in-overlay
      - OAUTH2_PROXY_WHITELIST_DOMAINS=set-in-overlay
      - OAUTH2_PROXY_COOKIE_SECURE=true
patches:
  - target:
      kind: HTTPRoute
      name: opencost
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: set-in-overlay
