---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: keycloak-instances
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgAP7V5s6I6Vk5l1LOuM+6ADDmWJEMKSmx2ryxTB4rVUovkhGIXkCTWfI7umPNM+WiJbvJz6+538qqpJ0IcuTH43GsHfNHG31RwM0Kcf1B/RxwaEL0u9nFecYrZu4Hxn4XuE6/afE568ZaYPB63fnYvtuRII/Z8sEhmhkTCZbvV9e3F9AEKcxaWNFDA1ki8heN48yyubqEo5qcNimwt6YAt/me8QzNpvOiuRdSmKehQV9unn+2tNDXQsjSo3ETclISE1bdmPkrt+62+LvNqk42cGz3HFntqX9eNByKR7e56flOh2+KmgTtekje0RoZp6FnS3jC+yg6xM5ZWuZveNZBQUsiVGdyxz843RABYCVmzg0yagBHk+BXr147ftMmPIG2QO2SCVnqXaCcKVm5hmAzFgDtMrjoes6ng1SBPVnp0/tbyh40XauHDOn7uk4Z9GnQhYblqRuY1KHH7sXQsOk0SuILJYygvxvxC8CPLZl1T26rBOI8/NdYkGAK5/souHCY2tzuACFmACnbiUG9KBS40hqAiNsCMqRSGGP1YMoPSMcGzxmOD5BQDmvNU1M+MQ0xjJnj+afRoEy1vzvYYR2berV70RYsIPXi8RWtGh+fNHtFbU0H4ZGz8Lw4H/YiXvo05/2JGch9+F9lGQNy88WarOxOp56PLfFGY/57yKkEaLniCkvdy4c1Enqq8oX93S+d8CphUGXXDqYF0=
  template:
    metadata:
      name: keycloak
      namespace: keycloak-instances
    type: Opaque
