apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: mono
spec:
  storage:
    traces:
      backend: memory
      size: 2Gi
  resources:
    total:
      requests: { cpu: 50m, memory: 384Mi }
      limits: { memory: 768Mi }
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
