apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-controller
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/external-secrets/controller/overlays/local
  prune: true
  wait: true
  dependsOn:
    - name: cluster-resources
    - name: kyverno-policies
    - name: sealed-secrets  # for now use sealed secrets for the openbao token, should be replaced in the future either by using SOPS or generating the secret via Taskfile

---
# CONFIG
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/external-secrets/config/overlays/local
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets-controller
    - name: openbao
