---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opencost-oauth2-proxy
  namespace: opencost
spec:
  encryptedData:
    OAUTH2_PROXY_CLIENT_SECRET: AgBGBqvPFJoq3yjESCFFg5MDzOx/V3A4cRhS85N7T8XwhBENhnqV6TCJe5sTRJUrznXAmS8VGBbtRqhFqlGv7uXkutqn0hXYg134wO7UZqR0xUqM5bg+OroXjSPDRG6mNkK+NnW6K23LJqczHZEx4UjaPeDwNj0YhGPLslsFE8TQ7RVuB41M3Tb9m7NiGXL6JV7IUrI4D8aFkCk8vH0vVnBggYnK2A6PWJazk/S3bHwovCxNuyeWXIR75iqdb91GwNFuETXFJluC9lLFRQaoAC818iWAfpI25OhIB5cVW9jlFj6d+lWznYBkSrotqSBa6/a7uI0pXWjN82yzzG/ACQHvgozWDJBDm09UX6Gu34HbEwMKSCQ1R0b1Rl+XiustTGFswg1ogSp8xSE1nPr9vdZ5ci7EkjQZ4rA/7/kgb/Y07PCcTkilVxOXCi0z/1W+BMPEAMioh2r7vMLxF1PRzdzGf7hghEliyHQuRm864uVkrydWe3RP9482h24JNeOD35SYjYTZ7HeW1CSXmNV8IbETbhW70/oW3k+gilpwAyvzjd14gG9wgKSIHPvkbEbdli5rUmDUss2cYYTeABrUrbicdhtW2axd6tLDRdE+vHwZ5Q8mCHiLwRmmKT9cciTVQFk+xoslfPQ8SNTNQotSDnDpqgvr5j/fs5T7G64/Jr0IxrFuVQuhnwTP2fBukCGFRhw5eW75EwRcBYA8vhCf04oWIUvbMK9xmacF
    OAUTH2_PROXY_COOKIE_SECRET: AgDEcNxuM4vg2Rgz7yAFHpVVBw82E1K/WZNjfi1XgA954gq2ZIC0vGLs7GWX8anTwo+bL5xgdLSYCS7+Oj1xITXH75CXG71b30BctoIm1UIlY22fRTBNeKwY+vJkY2VN2p63u5+4eMGqAgO8VTpF1cP/FqA7v+GkohRGz9WK/Pj4i2x5NxjQ+GyARnJsPOxjDSGBA+A+Mfw8ojDV3qwl1BLYFHoaBZaGVghtIiGG5kBCIr3c8BCaC60vDkP8o8mxUkxadW05kwCj6GyTV2/8EAsNJAOVC88dAMtwz1hcScJNIqBCH9kG/q/sqNdhYCYqLb8PuZ6+411We5jiwG70bV+E5EkawepPkKBN61sx65J3LGBfhJZ3cW1TwAcVNITrmgmx7srEMgRconQ9vd+92QHqH4S9WMb0tJPpDVc+ef0kmF2twTVk1ay1UxXLe39+9c6TotFIXvS0FBgJ6uXP87eZ6HrcFjg1uNfdWMqWJWXDN0WjCw7ctku4xMJ6C6GA69+E6GwXnucrGepBd+YslCZzO2pSR0G6y/6ieWsiV1Ub6MZw34cl0CUcSKTV3yeSnK0lgkYv1wf9Y4IRwhGO85515nhh//0tzT1hAddLuckP4ASGqPMlNbBXewa8s/C1ApfY8mnm0n4HcegreooJmcXlUDjF+Kr3I3nwuitkeiXviIN+Uma/mRGWTt07XVhmNHnhD86tTnIobPFvK29PTrI4gEENih5pnsOkRs9lgM2V5Q==
  template:
    metadata:
      name: opencost-oauth2-proxy
      namespace: opencost
    type: Opaque
