---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opencost-oauth2-proxy
  namespace: opencost
spec:
  encryptedData:
    OAUTH2_PROXY_CLIENT_SECRET: AgBSEgFHdm1aKqgBxsCTPfuZpZlA87tMPCpSgbku/xAK20iLzCYsKgNRzKNFxQqrTV80IvBRoIt9LL6a4Cg++E6HeeGKj8FeFsfRD9nLCfJrZLI9QPr92EmdRGtiuqRbTdD/3iI5Af06zGCrIg8NRAFtLqDte/3RC6tIRcIw4d6ZjnubEvomJO001if8s0EphuyZJR0VQfdoiVshyg1deUFzMeJ+RG47jzsXI8S3dAlRCjBd9HbJs8XClo7lFwNnF6vqQ62NZ98rdf6EyxlriCUhYm75fpumsii4tXbcAcPEniWlDq2Jkc5JRHlONFnDnGk1NV2XeH+wmtUYk9OwioCL0bSXN0XigWLCs49fYgn2vhamQ9ywXH0E/Y+/d8wRlIIL8uEfr+4h34r3WoBf6oAruEPOjn1iyQNGA9bdY1JX7sG7bgwldrhmbwm3IwALIWkR7BwvOH+/iRgFJ4XhOgr1ab55etbOW8IAtCVrS02V6c7zpnlW2mwewmC1q/uo2lAUwhy1xmOFHKVKWNSOPJHN24Uk0xfiHrtPTQV8J0EOWy/uFFzoM1c5NUBOF8VdlG1lSf7tg/eNoi9TCxxdSf66mbqCYUOLHmXTsDbca7q+2vpE69wDdwnTKrGj6OCtdrdyjUZQUyqNvtvS0iAVQIG1Z3FAHIDBLqp1xkTY5N6XZYn4hnm3edQ2b0w30/5BFGQhiJA39P+xGFT15Vn4w2NvgrShkwk3pDNl
    OAUTH2_PROXY_COOKIE_SECRET: AgCM3DXApxfpE2LS/U7noYsy+mIB8UzkmVXiofqCYpoqCa64Ip6BuuvrWrp6UbWvmd3j/tzNrLj0HF9ucFXnT/5hHUJGAjmVlxNwhZwhqEG3U8Rgmm53bw/8RItCBjqJXWa6mzbVIVOJCZnw4pRIwPK5z+MDYW2D86ZqJ+mYNgP6nnsYK6emoYv9y6r9IlpAIOo5yOoe9E9hb6R9a3dPcM5ijfabpnyd1AGUBaLX60CNVkCdjJOAjR6CwRKIpGM9DctbLUSmkzTzT/Xt7kNSDN3T3RfoLTAxn+UJzGLl8B7aT2NAKTTziI6KoHjABOsj7LDGAuukf5vTERu2nHmkWijpuCtLERUUzEWBa8NzTBDoQdE4CIYVcYSs57f/T73qs2d1mU5mt9pvYIYW09Klo6flN4J6A6zrEPbfCvEA59OuJTMgAxplBZML9ZpnvbHRl5q2rdWCEADxV3w171Dbl4+Z7q1aG17rb5kv0uYe6GFuGLkkm2IgCM4w4j3DvuC++arGe3DBuQI7SJlC8xsQp6N4rY2n4VqurMgStZBn2ARcHo89bfldWjEEXNOqVWyWOalvNdVRzQIjHcB8CUEOVQeYQdI6IlBL5Q9Vw9x0JesFoaxjBH/cmGeEQ7OKaigH4A4nJ4QAbXT2ysOjulpnYYyydz3BtkMSWjS8LItlCv5FGqgsG7/phuycWAECBaGuP4b3/iHkcFRTf7qqIFFuxVsNOWAc1vVA4hQdkJcCHaXNiQ==
  template:
    metadata:
      name: opencost-oauth2-proxy
      namespace: opencost
