apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: secret-from-bao-via-extsecrets
  data:
  - secretKey: foo1
    remoteRef:
      key: tenant-demo/example-secret
      property: foo1
  - secretKey: foo2
    remoteRef:
      key: tenant-demo/example-secret
      property: foo2
