apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-webhook-receiver-github.yaml
- flux-webhook-receiver-gitlab.yaml
- flux-webhook-token.yaml
- git-repository.yaml
- rbac.yaml
- sync.yaml
- example-secret.yaml
namespace: tenant-demo
