apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-backend
spec:
  provider:
    vault:
      server: http://openbao.openbao:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: tenant-demo
          serviceAccountRef:
            name: tenant-demo-auth
