apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-openzaak
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./tenants/openzaak
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: kyverno-policies
    - name: cloudnative-pg
    - name: istio-gateway
