apiVersion: v1
kind: Secret
metadata:
    name: s3-credentials
    namespace: mimir
type: Opaque
stringData:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:uQLpYE9hhGn7CrfWtf324Cs4nj75B6UUN9Q=,iv:l6kU/97z4cpdS8X4PrVvjFvNW9nF1GAJ4cvPLaDrR6M=,tag:bOT+hWzXHOd+IlTQ3Jw9/g==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lgoEpvgnevUDOQyPsA2Roc8LqvYW9ZTRJenphuvBPzYh8VMIWdsZiBAmfl33CK9Z0sAxaIu4yoTT4s4c5rrj2w==,iv:jywMRhpdU1I+iX+5oldBQvzzAi4pZE4wX+WKWdVhhdo=,tag:AQobeRQn2c1wjBb3GDkcqg==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd2JQbHNBQjBiRjVCcHJk
            V3IwY1F6MnRHaENWWkFFUzU4aTBaRTNIRHdjCkF0TUhtclNWVWNYN2Y0dGJ2RnND
            TmtpcDVyWFFjUXFxSk9UUnJrdi91OEUKLS0tIGVFT3Y1QXJsd2o5dC8xY0tqK2cw
            ZjBFb3FvQjFkdWRRY2RWQUtDbWUzTjAKiwAWW1xzLP5Mujwm7U6uK/Qf0gk6pnc9
            CA44Bu+FztdkuzoPb6Ltk2gSLcdllftdAdva687LPdZTrpIhAiY+tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T07:55:04Z"
    mac: ENC[AES256_GCM,data:4+msbDTzyOlEkFShN6Jqg7iQt9iuvElsJG5Kk63DYDFzS6UrpLs0XZnBK+RzwZ4cO22lthUAox4LtIJTk34gtXNleOMK+XtyIUGJNxnbGXSUjobTs0T6KeOHlzz+c3ZuAUFNEehDeq+s7W6fbD3r+zErqQmZK1tSX+OQR09U8ls=,iv:+uPJbHv86ReaNbybygSPWbU7s0GLkubyL+FhB+dKbNo=,tag:Cc3NwiLCd60kmNQscG8ZTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
