# CONTROLLER
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-controller
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/grafana/controller/overlays/havenpc
  prune: true
  wait: true
  dependsOn:
    - name: cluster-resources
    - name: kyverno-policies

---
# CONFIG
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-config
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/grafana/config/overlays/havenpc
  prune: true
  wait: true
  dependsOn:
    - name: cluster-resources
    - name: grafana-controller
    - name: cloudnative-pg
