---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openbao-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgCpeXtF9JHcEvaW89CockF44mXfU2awIg8K35SeMj7IOL833p/WGp0umuzh1FDOKXSn0eSquYrptIN5W50+Y17931HwKvibD5aUa030BaM2WiDesXiPwoWBOmj/bQ3CT8xYBC3lcZQ8vdwg+ATpwPJGQXl+RrcQWif8VO/NRIoW9Ox5CCLNjxN2I8swhes5dxLFBKuQ+h8/iS1z6tpEyRqPnWrRPuWK+m6Is5P580icik0P0+EzSMPfvOHTf/9OUdrhjg/LVE49KEqR0H97n+tJbkC6gDtfLaF86FHFCyHwpnsvvAeYrOS8MmNXT5tbwbw7i3EGqGPgPgYs97753zSXhuH60IOR84hjqqi+luX+irsLgcxBQZKDIeAS23ip3+8e4k4TWJ+qWcGCbUgTkjgfwh/ABGcmldtwxTBehVmxNi8LIAsFjFCmRBkgnJTKdtiFwHBzlKMCq2Mbr//ZQopLN8jyQ3CpZM/MHr7bUHOF0HVlRSXZwIjyIq9diICikWGgwSik/rrL4Oz9udAuy196QhzFCk3ZfcbHDvt2xamFHIwWBOX2z4kNadeC6O0utGPXnBx+g+woIhc8VLR9MDVYxvhZXF2rndnF8PI673AUPnpKx7zkd3Aw2trY6EYHQsoNHOvt9epHkuZC967rHn+vqnHiLTtiFbd/QwPF1i/gs/nTfuiypPK7JnQCX23osu9A7H//
  template:
    metadata:
      name: openbao-token
      namespace: external-secrets
