apiVersion: v1
kind: Secret
metadata:
    name: realm-havenpc
    namespace: keycloak-instances
type: Opaque
stringData:
    RICK_PASSWORD: ENC[AES256_GCM,data:pU51tfxaJYWivXrDcNPK3w==,iv:7N9MgXDoh53SsQ/LFzVxXUGAoT/aFrHA/LE68XxxRWw=,tag:aJWGPaOch6i/2jyCXEaiWw==,type:str]
    DEMO_PASSWORD: ENC[AES256_GCM,data:HklmVg5/+lGFdXU2wBMU,iv:BoTfUpoIqdHpbp/TkVw8wA4gao5tGz6jcydHO+Y/RQY=,tag:xFrQSu7H9Pi89I7FBIUZaA==,type:str]
    OPENZAAK_CLIENT_SECRET: ENC[AES256_GCM,data:HwIdjPStbiap2F6jerq2FTVAMkukufYh4tDNCeRgqdAy/bIdrERBSw==,iv:gVztrq0KYWWB5H5Dzv7Xs0bu+a75XHVqAHCyNDltkzY=,tag:MaqOU/IeR2ZI4ULn7gLXkA==,type:str]
    OPENNOTIFICATIES_CLIENT_SECRET: ENC[AES256_GCM,data:Bl14aCdNN/MF5HGpzfm7jrMWBDqcUhjULbZ3qEGhTro3OuUwoiI3vw==,iv:kqug5m/WQ8Rt+Oz521TbAagXylQ9ojBsNBLB46+NgRM=,tag:RBNrt1lRGEp2EVreXdLeow==,type:str]
    WERKPLEK_CLIENT_SECRET: ENC[AES256_GCM,data:lxSqQv0I4gDzZoUB1we9eesrzuuIuhyY02uVbvvgFtzU8CYP5Qm3L5HsGekLIgXtVwkYWdCMtM/0qDczYSmQeQ==,iv:8EgG229Bfs1/uzAY9GDoZF1qVoYj5Hi2z9eSDb+t8iA=,tag:AtwKAuTcyU94bVI501awsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTldQeG9SZm1wTktTUzJo
            VDJId3hrTGRDcWxTbE55L0JTTHhvcFY1MjNJClJJRytMN0pSVnc5S1cxNGZPSFUv
            UzRBZ2RQdEZkK2djMEY4bVVCK1ZCSncKLS0tIC9ZanQ5NmZSUlBsT2F0MTduT1V2
            dVhWRE0zSUtuUUFzWmxjY3IvRzRnODQKxOGMBUscWrGILhQE8RKnBq7Tsc41zl6U
            tL9ZMSGjRajNTvmzbIo2r8HkAD75ltmlYNBW2NzIYACCygL2AV9U3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T15:57:59Z"
    mac: ENC[AES256_GCM,data:7z5ie3LYB9OiqB+bnre3/fhwA2ynMhb2FSYSf6T0W1pOL1CqG1QEFHoOREZGk9QVTymIKg543GBTGrdt/ATp9SWd3QgLyarLwuSQQ06uB4jTTWZJWB+fDJWxL4oaNvp48SdoViZNmXItmqqro5LFVVdkULSHy/yEYJb66dNW04M=,iv:qUrt2vmlZ2IvQLYHLoLMqBIHU0XYwxOVj5+RrbB/IEk=,tag:gvONJYG9yLHdFv/5hRW85g==,type:str]
    version: 3.13.3
