apiVersion: v1
kind: Secret
metadata:
    name: keycloak
    namespace: keycloak-instances
type: Opaque
stringData:
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:RiV8VXbEb2Gz6XKGJ3xKYT/agvv9azVA,iv:p8oFKPKulcm3VwQ/RKnh6+8rdeXF07vPl8BcZX5M/zU=,tag:xLEFcm1o4GtqAvmOKKnyHQ==,type:str]
sops:
    age:
        - recipient: age130vs6nqtwyhsq6kj7s6u2al665n7wvnwdjx7032s7jamrpyw43esq64xfn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSFFtRGxxQVJaSGg2cDdP
            VmZWbHBnUXZ0ZzJGOUNYUFFBUWZXRnBsS1I4CnIxbUY5ZGtNUmxxcVZnWUlCa3lJ
            RkRHTzRqT05RRThFNzV4cVFjRi9IdFUKLS0tIGZGUWFtOHdoaXRKSE55RHpzR1FG
            WG53a2lTNEw0Y2hhTGJoeVhBUWFSaUkKtGAyc5ondxX1kfyDnbEqWDgbn6qyDq3z
            NlIJJDU+IXliQcGCF4NeemT3ZE6JphXrtMo2PSq8Lzm9Kbsb/A/+6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T07:49:52Z"
    mac: ENC[AES256_GCM,data:pHfme0yt8zBGnGxMsESgD3ob9ireTaqx2Ye6FsnpLKlEmwhpOyURnVWXZYrOGM/GQ+tzh9c7fxaaIXWleSZbZFdpC/lsYpoTk83E6V2n0l3LDcAXbEtWrq1Y+626V88mPJejF+JsmyaROVnBp7xpsHQ88gUet+7Ub3228IzOiGQ=,iv:5NPkmqPO68RihwuVP08H1wnadCGnEv2lApC8FE/3DgQ=,tag:jBlUMGPZ2Nv1I9dhC4lbKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
