apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  chart:
    spec:
      version: "3.4.4"
  values:
    policyExclude:
      disallow-capabilities:
        any:
        - resources:
            namespaces:
            - istio-system
            - nfs-server-provisioner
      disallow-host-namespaces:
        any:
        - resources:
            namespaces: []
      disallow-host-path:
        any:
        - resources:
            namespaces:
            - falco
            - istio-system
            - local-path-storage
            - trivy-system
            - velero # needed for the node-agent daemonset which does file-system-backup
      disallow-host-ports:
        any:
        - resources:
            namespaces: []
      disallow-host-process:
        any:
        - resources:
            namespaces: []
      disallow-privileged-containers:
        any:
        - resources:
            namespaces:
            - falco
      disallow-proc-mount:
        any:
        - resources:
            namespaces: []
      disallow-selinux:
        any:
        - resources:
            namespaces: []
      restrict-apparmor-profiles:
        any:
        - resources:
            namespaces:
            - istio-system
      restrict-seccomp:
        any:
        - resources:
            namespaces: []
      restrict-sysctls:
        any:
        - resources:
            namespaces: []
      disallow-capabilities-strict:
        any:
        - resources:
            namespaces:
            - istio-system
            - local-path-storage
            - previder-staas # nfs-subdir-external-provisioner
            - falco
            - velero
      disallow-privilege-escalation:
        any:
        - resources:
            namespaces:
            - istio-system
            - local-path-storage
            - previder-staas # nfs-subdir-external-provisioner
            - falco
            - velero
      require-run-as-non-root-user:
        any:
        - resources:
            namespaces:
            - istio-system
            - trivy-system
            - previder-staas # nfs-subdir-external-provisioner
            - falco
            - velero
      require-run-as-nonroot:
        any:
        - resources:
            namespaces:
            - istio-system
            - local-path-storage
            - trivy-system # trivy needs to be root in order to be able to scan filesystems
            - previder-staas # nfs-subdir-external-provisioner
            - falco
            - velero
      restrict-seccomp-strict:
        any:
        - resources:
            namespaces:
            - local-path-storage
            - falco
            - velero
        - resources:
            selector:
              matchLabels:
                app.kubernetes.io/name: ztunnel
      restrict-volume-types:
        any:
        - resources:
            namespaces:
            - istio-system
            - previder-staas # nfs-subdir-external-provisioner uses hostPath for NFS mounts
            - falco
